version: "3.8"

services:
   db:
      image: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=${POSTGRES_DB}
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      env_file:
         - .env
   web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
         - .:/Test_ipoteka
      ports:
         - "8000:8000"
      depends_on:
         - db
   test:
     build: .
     command: python3 manage.py test ipoteka.tests
     volumes:
        -  .:/test_ipoteka_tests
     depends_on:
       - db
       - web


volumes:
   postgres_data: